#数据库信息
database:
  root: "root"
  password: "password"
  host: "localhost"
  port: 3307
  dbname: "mysql"
  charset: "utf8mb4"
  parseTime: "True"
  loc: "Local"
#鉴权信息
jwt:
  Issuer: "Echin"
  Subject: "Tom"
  SecretKey: "ItIsSecret"